### ISSUE TITLE
Noble Node12

### ISSUE THREAD

**Issue by MathiasJZ** [AlCalzone/ioBroker.ble#383]
I made a test installation of iobroker.
But iobroker.ble didn't worked.
Noble is already updated to use your adapter also with nodejs 12?

**Comment by AlCalzone** [comment]
Can you try to install the version that is currently on GitHub and see if that works?

**Comment by MathiasJZ** [comment]
BLE Adapter is green but no changes here.
I took a xiapmi plantsensor in a glas of water. But still 38 percent. It must be 100 percent....

**Comment by AlCalzone** [comment]
I don't think the air humidity above a glass of water is 100%. If you turn the loglevel of the adapter to debug, do you see that the adapter receives data?

**Comment by MathiasJZ** [comment]
I really like to make it again. But it's my slave of my Multihost.
I don't have a adiitional Raspberry for testing now.

Am 13. April 2020 19:17:26 schrieb AlCalzone <notifications@github.com>:

**Comment by Ilovegym66** [comment]
it's not fixed, with Node 12.16.2 and js-controller 3.0.8 the ble adapter looks like working for some seconds, goes to red and this is in the logfile:
`

ble.0 | 2020-04-14 22:07:07.007 | info | (3430) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
ble.0 | 2020-04-14 22:07:07.005 | info | (3430) terminating
ble.0 | 2020-04-14 22:07:06.996 | error | (3430) unhandled promise rejection: Error: undefined is not a valid state value
ble.0 | 2020-04-14 22:07:06.993 | info | (3430) stopping scan
ble.0 | 2020-04-14 22:07:06.990 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
ble.0 | 2020-04-14 22:07:06.990 | error | at fulfilled (/opt/iobroker/node_modules/iobroker.ble/build/main.js:5:58)
ble.0 | 2020-04-14 22:07:06.990 | error | at Generator.next (<anonymous>)
ble.0 | 2020-04-14 22:07:06.990 | error | at Noble.<anonymous> (/opt/iobroker/node_modules/iobroker.ble/build/main.js:331:35)
ble.0 | 2020-04-14 22:07:06.990 | error | at Adapter.setStateChangedAsync (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1566:16)
ble.0 | 2020-04-14 22:07:06.990 | error | at new Promise (<anonymous>)
ble.0 | 2020-04-14 22:07:06.990 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1567:16
ble.0 | 2020-04-14 22:07:06.990 | error | at Adapter.setStateChanged (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5833:21)
ble.0 | 2020-04-14 22:07:06.990 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1570:39
ble.0 | 2020-04-14 22:07:06.990 | error | (3430) Error: undefined is not a valid state value
ble.0 | 2020-04-14 22:07:06.984 | error | (3430) uncaught exception: undefined is not a valid state value
ble.0 | 2020-04-14 22:07:06.716 | info | (3430) starting scan for services []

`

**Comment by Ilovegym66** [comment]
a scan with hcitool lescan is working fine and list a lot of devices.

**Comment by Phillipp83** [comment]
Hallo ich glaube es gibt ebenfalls ein Problem mit dem Node.js v10.20.1 update.
Nach dem ich es auf zwei verschiedenen Systemen habe, wollte ich mal bescheid geben. Nach dem dich auf meinem Debian (intel NUC System) als auch auf meinem Armbian (Tinkerboard System) den Node.js auf v10.20.1 update, geht der Adapter nicht mehr.  _bluetooth driver state "unknown"_

debug: 
`ble.0	2020-04-15 01:40:06.746	info	(3755) monitored services: fe95
ble.0	2020-04-15 01:40:06.744	info	(3755) enabled plugins: Xiaomi, _default
ble.0	2020-04-15 01:40:06.743	info	(3755) loaded plugins: Xiaomi, mi-flora, ruuvi-tag, _default
ble.0	2020-04-15 01:40:06.674	debug	(3755) Schedule restart: * * * * *
ble.0	2020-04-15 01:40:06.564	info	(3755) starting. Version 0.11.1 in /opt/iobroker/node_modules/iobroker.ble, node: v10.20.1
host.tinkerboard	2020-04-15 01:40:04.975	info	instance system.adapter.ble.0 started with pid 3755
host.tinkerboard	2020-04-15 01:40:03.913	info	Restart adapter system.adapter.ble.0 because enabled
host.tinkerboard	2020-04-15 01:40:03.912	error	instance system.adapter.ble.0 terminated with code 156 (156)
ble.0	2020-04-15 01:40:00.047	info	(3737) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
ble.0	2020-04-15 01:40:00.042	info	(3737) terminating
ble.0	2020-04-15 01:40:00.023	info	(3737) Scheduled restart.
ble.0	2020-04-15 01:39:57.295	info	(3737) monitored services: fe95
ble.0	2020-04-15 01:39:57.293	info	(3737) enabled plugins: Xiaomi, _default
ble.0	2020-04-15 01:39:57.292	info	(3737) loaded plugins: Xiaomi, mi-flora, ruuvi-tag, _default
ble.0	2020-04-15 01:39:57.227	debug	(3737) Schedule restart: * * * * *
ble.0	2020-04-15 01:39:57.131	info	(3737) starting. Version 0.11.1 in /opt/iobroker/node_modules/iobroker.ble, node: v10.20.1
host.tinkerboard	2020-04-15 01:39:55.542	info	instance system.adapter.ble.0 started with pid 3737
host.tinkerboard	2020-04-15 01:39:55.515	info	"system.adapter.ble.0" enabled`

Nach dem ich das ganze System neu aufgesetzt habe mit Node.js 10.20.1 ohne Backup und nur den Bluetooth Adapter 0.11.1 installiert habe ist wider alles grün.

**Comment by Apollon77** [comment]
Schedule restart: * * * * * ??? Das heisst restart jede Minute???

**Comment by AlCalzone** [comment]
> bluetooth driver state "unknown"

Hier stimmt irgendwas mit dem Bluetooth-Stack nicht, was leider außerhalb der Kontrolle des Adapters liegt.

> Error: undefined is not a valid state value

Und das ist neu in JS-Controller 3.0 😅

**Comment by Phillipp83** [comment]
@Apollon77  Das sollte eigentlich jede stunde sein. Weil nach einer weile keine Daten mehr empfangen wurde.
@AlCalzone Das Problem ist aber erst aufgetreten nach dem ich die neue Node.js 10.20.1 installiert habe. 
Also wenn ich euch beiden deuten soll heißt es für mich einmal neu aufsetzen. :-(

**Comment by AlCalzone** [comment]
@Phillipp83 hast du nach dem Node.js-Update den Fixer ausgeführt? Wenn nein, mach das!

**Comment by Phillipp83** [comment]
@AlCalzone ich habe nur die befehle eingegeben.
`sudo apt-get update
sudo apt-get upgrade
sudo apt-get install curl build-essential
sudo curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
sudo apt-get install -y nodejs`

wie lautet den der Fixer befehl?

**Comment by Phillipp83** [comment]
@AlCalzone oh mein gott. **DANKE** 
ich habe eben 
`curl -sL https://iobroker.net/fix.sh | bash -`
eingegeben und es lauft alles. 
ich habe das jetzt zu meinen Notizen hinzugefügt.
Dann wundere ich mich dass es sonst auch so geklappt hat. :-) 
Danke noch mal.

**Comment by AlCalzone** [comment]
Kann irgendwer bestätigen ob der adapter unter node 12 läuft oder nicht läuft?

**Comment by MathiasJZ** [comment]
Ich kann nur so viel sagen, dass ich keine Werte bekam, egal von welchem 
Xiaomi plant Sensor.
Danach habe ich die andere SD Karte wieder gewechselt. Will ja nicht, dass 
die armen Pflanzen verdursten


Am 18. April 2020 13:35:36 schrieb AlCalzone <notifications@github.com>:

**Comment by Apollon77** [comment]
Kannst du es bitte nochmal versuchen mit der aktuellen Version?

**Comment by AlCalzone** [comment]
> Kannst du es bitte nochmal versuchen mit der aktuellen Version?

Github bitte, ich habe noch keine neue auf npm gepublished

**Comment by Ilovegym66** [comment]
Hallo Ihr :-) 
Gerade auf dem Raspi mal ble komplett sauber gelöscht, Node 12.6, js-controller 3.0.13, admin 4.0.8. Mit apt-get update && upgrade aktuell, dann von Git den ble adapter gezogen, installiert, hochgeladen, gleicher Fehler wieder. Der Adapter startet, legt objecte an, findet auch alles mögliche, und beendet sich. Hab dann mal ein npm rebuild gemacht, keine Änderung.

`

host.zweiberry | 2020-04-18 20:01:05.713 | info | Do not restart adapter system.adapter.ble.0 because disabled or deleted
-- | -- | -- | --
host.zweiberry | 2020-04-18 20:01:05.711 | error | instance system.adapter.ble.0 terminated with code 3 (NO_ADAPTER_CONFIG_FOUND)
ble.0 | 2020-04-18 20:01:04.999 | warn | (14185) Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
ble.0 | 2020-04-18 20:01:04.923 | error | (14185) adapter disabled
host.zweiberry | 2020-04-18 20:00:52.544 | info | "system.adapter.ble.0" disabled
host.zweiberry | 2020-04-18 20:00:32.053 | info | Restart adapter system.adapter.ble.0 because enabled
host.zweiberry | 2020-04-18 20:00:32.051 | info | instance system.adapter.ble.0 terminated with code 0 (NO_ERROR)
ble.0 | 2020-04-18 20:00:31.276 | info | (14166) Terminated (NO_ERROR): Without reason
ble.0 | 2020-04-18 20:00:31.274 | info | (14166) terminating
ble.0 | 2020-04-18 20:00:31.225 | error | (14166) unhandled promise rejection: Error: undefined is not a valid state value
ble.0 | 2020-04-18 20:00:31.222 | info | (14166) stopping scan
ble.0 | 2020-04-18 20:00:31.219 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
ble.0 | 2020-04-18 20:00:31.219 | error | at fulfilled (/opt/iobroker/node_modules/iobroker.ble/build/main.js:5:58)
ble.0 | 2020-04-18 20:00:31.219 | error | at Generator.next (<anonymous>)
ble.0 | 2020-04-18 20:00:31.219 | error | at Noble.<anonymous> (/opt/iobroker/node_modules/iobroker.ble/build/main.js:331:35)
ble.0 | 2020-04-18 20:00:31.219 | error | at Adapter.setStateChangedAsync (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1566:16)
ble.0 | 2020-04-18 20:00:31.219 | error | at new Promise (<anonymous>)
ble.0 | 2020-04-18 20:00:31.219 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1567:16
ble.0 | 2020-04-18 20:00:31.219 | error | at Adapter.setStateChanged (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5833:21)
ble.0 | 2020-04-18 20:00:31.219 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1570:39
ble.0 | 2020-04-18 20:00:31.219 | error | (14166) Error: undefined is not a valid state value
ble.0 | 2020-04-18 20:00:31.212 | error | (14166) uncaught exception: undefined is not a valid state value
ble.0 | 2020-04-18 20:00:28.523 | info | (14166) starting scan for services []
ble.0 | 2020-04-18 20:00:28.220 | info | (14166) monitoring all services
ble.0 | 2020-04-18 20:00:28.218 | info | (14166) enabled plugins: Xiaomi, mi-flora, _default
ble.0 | 2020-04-18 20:00:28.214 | info | (14166) loaded plugins: Xiaomi, mi-flora, ruuvi-tag, _default
ble.0 | 2020-04-18 20:00:28.052 | info | (14166) starting. Version 0.11.1 in /opt/iobroker/node_modules/iobroker.ble, node: v12.16.2, js-controller: 3.0.13
host.zweiberry | 2020-04-18 20:00:26.769 | info | Update repository "Latest1" under "http://iobroker.live/repo/sources-dist-latest.json"
host.zweiberry | 2020-04-18 20:00:25.653 | info | iobroker exit 0
host.zweiberry | 2020-04-18 20:00:24.876 | info | instance system.adapter.ble.0 started with pid 14166
host.zweiberry | 2020-04-18 20:00:24.586 | info | iobroker Update "system.adapter.ble.0"
host.zweiberry | 2020-04-18 20:00:24.387 | info | iobroker upload [0] ble.admin /opt/iobroker/node_modules/iobroker.ble/admin/ble.png ble.png image/png
host.zweiberry | 2020-04-18 20:00:24.307 | info | iobroker upload [1] ble.admin  /opt/iobroker/node_modules/iobroker.ble/admin/build/index.js  build/index.js application/javascript
host.zweiberry | 2020-04-18 20:00:24.209 | info | iobroker upload [2] ble.admin  /opt/iobroker/node_modules/iobroker.ble/admin/build/index.js.map  build/index.js.map application/json
host.zweiberry | 2020-04-18 20:00:24.113 | info | iobroker upload [3] ble.admin /opt/iobroker/node_modules/iobroker.ble/admin/build/index.map build/index.map application/json
host.zweiberry | 2020-04-18 20:00:24.047 | info | iobroker upload [4] ble.admin /opt/iobroker/node_modules/iobroker.ble/admin/index.html index.html text/html
host.zweiberry | 2020-04-18 20:00:23.985 | info | iobroker upload [5] ble.admin /opt/iobroker/node_modules/iobroker.ble/admin/index_m.html index_m.html text/html
host.zweiberry | 2020-04-18 20:00:23.922 | info | iobroker upload [6] ble.admin /opt/iobroker/node_modules/iobroker.ble/admin/src/index.tsx src/index.tsx null
host.zweiberry | 2020-04-18 20:00:23.826 | info | iobroker upload [7] ble.admin /opt/iobroker/node_modules/iobroker.ble/admin/src/lib/admin.d.ts src/lib/admin.d.ts video/mp2t
host.zweiberry | 2020-04-18 20:00:23.760 | info | iobroker upload [8] ble.admin /opt/iobroker/node_modules/iobroker.ble/admin/src/pages/settings.tsx src/pages/settings.tsx null
host.zweiberry | 2020-04-18 20:00:23.564 | info | iobroker upload [9] ble.admin /opt/iobroker/node_modules/iobroker.ble/admin/style.css style.css text/css
host.zweiberry | 2020-04-18 20:00:23.468 | info | iobroker upload [10] ble.admin /opt/iobroker/node_modules/iobroker.ble/admin/tsconfig.json tsconfig.json application/json
host.zweiberry | 2020-04-18 20:00:22.893 | info | iobroker upload [11] ble.admin /opt/iobroker/node_modules/iobroker.ble/admin/words.js words.js application/javascript
host.zweiberry | 2020-04-18 20:00:06.870 | info | Restart adapter system.adapter.ble.0 because enabled

`

**Comment by Ilovegym66** [comment]
Seit wann erkennt der Dashbuttons???
![grafik](https://user-images.githubusercontent.com/36229898/79645457-e174a780-81af-11ea-8db4-e93d0a9fb171.png)

**Comment by AlCalzone** [comment]
Ach verdammt da war ja noch was. Werde ich morgen fixen und dann nochmal bescheid geben.

**Comment by AlCalzone** [comment]
Ist aktualisiert, bitte aktuellste Github-Version probieren.

**Comment by Ilovegym66** [comment]
Dankeschön, läuft! Hab den auf 2 Raspis laufen, wurden beide von Node10 auf Node12 geupdatet, in Verbindung mit js-controller 3.0.13, Admin 4.08. 

Werte kommen rein, keine Warnings oder Errors im Log.
Issue kann zu gemacht werden.

**Comment by AlCalzone** [comment]
Prima, danke für den Test!

**Comment by AlCalzone** [comment]
v0.11.2 ist in Kürze auf verfügbar

**Comment by MathiasJZ** [comment]
v0.11.2 arbeitet hier einwandfrei!
Derzeit nur im Multihost slave, weil Radar2 wird immer noch nicht gehen.
