### ISSUE TITLE
Not working on Slave hosts

### ISSUE THREAD

**Issue by nob0dy80** [AlCalzone/ioBroker.ble#46]
Using iobroker master in the basement and only the slave on a raspberry is running in my flat for getting bluetooth and zigbee devices (so zigbee and ble are the only adapters running on slave).

Well lets make it short:
startInstance system.adapter.ble.0: required adapter "admin" not found!

Admin Adapter is only running active on master host.
Dont even know why he needs admin adapter..this is the first adapter that is making problems to me running on a slave

**Comment by AlCalzone** [comment]
> Dont even know why he needs admin adapter..this is the first adapter that is making problems to me running on a slave

The adapter needs an admin instance to be configured. Because there is no longer an admin page for admin v2, this requires admin v3. In theory, the admin may be installed on any host in a multihost environment. Unfortunately, there's a bug in JS-Controller, that only checks on the current host:
https://github.com/ioBroker/ioBroker.js-controller/issues/325

**Comment by AlCalzone** [comment]
Fixed in 0.7.4
